apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamedmagdy122/ecommerce-gitops
    targetRevision: main
    path: .
    helm:
      chart: ecommerce-frontend
      valueFiles:
        - environments/stg/ecommerce-ui.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
