{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.keys }}
    - secretKey: {{ .localKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteSecretName }}
        property: {{ .remoteKey }}
    {{- end }}
{{- end }}
